name: Build and Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/**'

permissions:
  contents: read
  pages: write
  id-token: write
