name: Unzip and Commit

on:
  workflow_dispatch:   # تشغيل يدوي من Actions
  push:
    paths:
      - "*.zip"        # يشتغل لو في ملف zip اتضاف

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install unzip
        run: sudo apt-get install -y unzip

      - name: Extract ZIP
        run: |
          mkdir extracted
          unzip "*.zip" -d extracted

      - name: Commit extracted files
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          cp -r extracted/* .
          rm -rf extracted
          git add .
          git commit -m "Unzipped project files"
          git push
